### ISSUE TITLE
How to convert an mp3 file into .nbs ? 

### ISSUE THREAD

**Issue by Misteboss** [thatcraniumguy/Songs#1]
How to convert an mp3 file into .nbs ?

**Comment by thatcraniumguy** [comment]
I've only been able to convert midi to nbs. I use Minecraft Note Block
Studio.

**Comment by stefvanschie** [comment]
I usually find the sheet music for a specific song and copy all notes into minecraft note block studio by hand. It's very tedious, but your song will end up perfectly. If there's no sheet music you can try to find a .mp3 to .midi converter and then use the built in converter in minecraft note block studio to get a .nbs file. Keep in mind that it usually sounds horrible this way, though.

**Comment by Dinoway** [comment]
Minecraft Note Block Studio allows you to export mp3 files

**Comment by thatcraniumguy** [comment]
The issue was to convert from .mp3 TO .nbs, not the other way around.

**Comment by gege12222** [comment]
a
